name: Publish to Maven repository 

on:
  push:
    tags:
      - v*

jobs:
  publish:
    if: false  # ⛔ prevents this job from ever running
    uses: Greenfossil/.github/.github/workflows/publish-release.yml@main
    secrets: inherit
      
