name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: false  # ⛔ prevents this job from ever running
    uses: Greenfossil/.github/.github/workflows/run-tests.yml@main
    secrets: inherit
      
